name: "Steamfetch"
description: "This action is a wrapper for DepotDownloader which is used to download files from Steam."
branding:
  icon: "download"
  color: "gray-dark"
inputs:
  username:
    description: "Optionally provide Steam account username. If unspecified then we'll log in anonymously."
    required: false
    default: ""
  password:
    description: "Optionally provide Steam account password. If unspecified then we'll log in anonymously."
    required: false
    default: ""
  dir:
    description: "The directory in which to place the downloaded files."
    required: true
  os:
    description: "Decides which version of the game is downloaded. Possible values are windows, macos, linux."
    required: true
  files:
    description: "Optionally provide an array of files to download. If unspecified all files will be downloaded."
    required: false
    default: ""
  app:
    description: "The id of the application to download."
    required: true
  beta:
    description: "Optionally specify which beta branch to download. Default is Public."
    required: false
    default: "Public"
  beta-password:
    description: "Optionally specify a password for the beta branch."
    required: false
    default: ""
  osarch:
    description: "Target OS architecture to download. Possible values are 32, 64."
    required: true
  loginid:
    description: "Optionally specify a unique login 32bit integer. Required if running multiple instances of this action concurrently, or if you don't want steam friends to get signed out when using a personal account."
    required: false
    default: ""
  language:
    description: "Optionally specify a language. Default is english."
    required: false
    default: "english"
  max-downloads:
    description: "Optionally specify maximum numbers of chunks to download concurrently. Default is 8."
    required: false
    default: "8"
  max-servers:
    description: "Optionally specify maximm number of content servers to use. Default is 20."
    required: false
    default: "20"
  cellid:
    description: "Optionally override the cell id of the content server to download from."
    required: false
    default: ""
  pubfile:
    description: "Optionally specify the published file id to download (will automatically resolve to UGC id). Used for downloading from the workshop."
    required: false
    default: ""
  ugc:
    description: "Optionally specify the UGC id to download. Used for downloading from the workshop."
    required: false
    default: ""
  manifest:
    description: "Optionally specify which manifest id to download. Requires depot to be specified."
    required: false
    default: ""
  depot:
    description: "Optionally specify the depot id to download. Required if downloading a specific manifest."
    required: false
    default: ""
  keep-depotdownloader:
    description: "If true then the .DepotDownloader folder will not be deleted from the out directory."
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: "Setup dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - name: "Download DepotDownloader"
      uses: "suisei-cn/actions-download-file@v1"
      with:
        url: "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.4.6/depotdownloader-2.4.6.zip"
        target: "${{ github.action_path }}/depotdownloader/"
    - run: "unzip -o ./depotdownloader-2.4.6.zip -d ./"
      working-directory: "${{ github.action_path }}/depotdownloader/"
      shell: bash
    - run: chmod +x $GITHUB_ACTION_PATH/job.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/job.sh
      shell: bash
      working-directory: "${{ github.action_path }}"
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_DIR: ${{ inputs.dir }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_APP: ${{ inputs.app }}
        INPUT_BETA: ${{ inputs.beta }}
        INPUT_BETA_PASSWORD: ${{ inputs.beta-password }}
        INPUT_OSARCH: ${{ inputs.osarch }}
        INPUT_LOGINID: ${{ inputs.loginid }}
        INPUT_LANGUAGE: ${{ inputs.language }}
        INPUT_MAXDOWNLOADS: ${{ inputs.max-downloads }}
        INPUT_MAXSERVERS: ${{ inputs.max-servers }}
        INPUT_CELLID: ${{ inputs.cellid }}
        INPUT_PUBFILE: ${{ inputs.pubfile }}
        INPUT_UGC: ${{ inputs.ugc }}
        INPUT_MANIFEST: ${{ inputs.manifest }}
        INPUT_DEPOT: ${{ inputs.depot }}
        INPUT_KEEP_DEPOTDOWNLOADER: ${{ inputs.keep-depotdownloader }}
